<a href="https://colab.research.google.com/github/get-programmed/Python_For_Analysis/blob/main/Import_table_from_external_website.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Import table from external ebsite using python**

In [2]:
import pandas as pd

In [3]:
url = 'https://en.wikipedia.org/wiki/Production_car_speed_record'

dfs = pd.read_html(url)

* The `read_html()` function requires a parser to handle the HTML content.
* By default, it uses the `bs4` parser, which requires the `BeautifulSoup` library.
* Since `BeautifulSoup` is not a mandatory dependency for Jupyter notebooks running on Linux, it's recommended to use the `html5lib` parser instead.

---
---

In [4]:
df = dfs[1]

The code `df = dfs[1]` assigns the second element of the list dfs to the variable df.

Here's what the code does:

* `dfs`: This is a list that contains multiple DataFrames.
* `[1]`: This is the index of the second element in the list.
* `df = dfs[1]`: This assigns the second element (which is a DataFrame) to the variable df.

In [5]:
dfs[1]

,Year,Make and model,Top speed,Engine,Number built,Comment
0,1951,Pegaso Z-102,245 km/h (152 mph),"3,178 cm3 (193.9 cu in) V8 268 kW (365 PS; 360...",84,360 hp turbocharged variant. Tested by Belgian...
1,1959,Maserati 5000 GT,277 km/h (172.4 mph),"4,935 cm3 (301.2 cu in) V8 254 kW (345 PS; 340...",2,No accurate measurement and only the first two...
2,1959,Maserati 5000 GT,277 km/h (172.4 mph),"4,941 cm3 (301.5 cu in) V8 242 kW (330 PS; 325...",32,No accurate measurement and only the first two...
3,1985,Lamborghini Countach 5000QV,298 km/h (185 mph)[37],"5,167 cm3 (315.3 cu in) V12 335 kW (455 PS; 44...",676,"Tested by Auto, Motor und Sport. The car which..."
4,1990,Vector W8,389 km/h (242 mph) for prototype,"5,973 cm3 (364.5 cu in) twin-turbocharged V8 4...",17 production models,"No verified top speed for production model, 35..."
5,1992,Jaguar XJ220,338.8 km/h (210.5 mph)[39],"3,498 cm3 (213.5 cu in) twin-turbocharged V6 4...",281,Tested by Road & Track. The 349.4 km/h (217.1 ...
6,2004,Koenigsegg CCR,387.866 km/h (241.009 mph),"4,700 cm3 (290 cu in) twin-supercharged V8 601...",14,Recorded at the Nardò Ring testing facility on...
7,2014,Hennessey Venom GT,435.31 km/h (270.49 mph)[1],"7,000 cm3 (430 cu in) twin-turbocharged V8 928...",16,Single direction top speed test run in 2014 an...
8,2019,Bugatti Chiron Super Sport 300+,490.484 km/h (304.773 mph),"8,000 cm3 (490 cu in) quad-turbocharged W16 1,...",100-110[i],"On 2 August 2019, Andy Wallace achieved a maxi..."
9,2022,SSC Tuatara,475 km/h (295 mph),"5,900 cm3 (360 cu in) twin-turbocharged V8 1,3...",100 (production to commence),"On May 14, 2022, Larry Caplin’s Tuatara reache..."

In [6]:
styled_table = df.iloc[:3].style.set_table_attributes("class='mytable'").set_properties(**{'text-align': 'left'})

display(styled_table)

The code `styled_table = df.iloc[:3].style.set_table_attributes("class='mytable'").set_properties(**{'text-align': 'left'})` creates a styled DataFrame with the following characteristics:

* Only the first 3 rows of the DataFrame `(df.iloc[:3])` are included.
* The CSS class `mytable` is applied to the table element.
* The text alignment of all cells is set to left.
Here's a breakdown of what the code does:

* `df.iloc[:3]`: This selects the first 3 rows of the DataFrame using the iloc attribute.
* `.style`: This accesses the Pandas styling object associated with the selected rows.
* `.set_table_attributes("class='mytable'")`: This sets the class attribute of the table element to mytable.
* `.set_properties({'text-align': 'left'})`**: This sets the text alignment of all cells in the table to left.
* `display(styled_table)`: This displays the styled DataFrame as an HTML table.
When you run this code, you will see a table with the following properties:

* Only the first 3 rows of the DataFrame are displayed.
* The table has a CSS class called `mytable`.
* The text in all cells is aligned to the left.

---
---